package com.jerry155756294.powerampbridge.protocol

object ProtocolConstants {
  const val Player = "player"
  const val Protocol = "protocol"
  const val Init = "init"
  const val PluginVersion = "pluginversion"
  const val PlayerStatus = "playerstatus"
  const val PlayerState = "playerstate"
  const val PlayerRepeat = "playerrepeat"
  const val PlayerShuffle = "playershuffle"
  const val PlayerMute = "playermute"
  const val PlayerVolume = "playervolume"
  const val PlayerPlayPause = "playerplaypause"
  const val PlayerPlay = "playerplay"
  const val PlayerPause = "playerpause"
  const val PlayerStop = "playerstop"
  const val PlayerNext = "playernext"
  const val PlayerPrevious = "playerprevious"
  const val NowPlayingTrack = "nowplayingtrack"
  const val NowPlayingPosition = "nowplayingposition"
  const val NowPlayingDetails = "nowplayingdetails"
  const val NowPlayingList = "nowplayinglist"
  const val NowPlayingQueue = "nowplayingqueue"
  const val NowPlayingCover = "nowplayingcover"
  const val NowPlayingLyrics = "nowplayinglyrics"
  const val PlaylistList = "playlistlist"
  const val PlaylistPlay = "playlistplay"
  const val RadioStations = "radiostations"
  const val BrowseGenres = "browsegenres"
  const val BrowseArtists = "browseartists"
  const val BrowseAlbums = "browsealbums"
  const val BrowseTracks = "browsetracks"
  const val LibraryCover = "libraryalbumcover"
  const val LibraryPlayAll = "libraryplayall"
  const val PlayerOutput = "playeroutput"
  const val PlayerOutputSwitch = "playeroutputswitch"
  const val Ping = "ping"
  const val Pong = "pong"
  const val VerifyConnection = "verifyconnection"
  const val CommandUnavailable = "commandunavailable"
  const val NotAllowed = "notallowed"
  const val UnknownCommand = "unknowncommand"
  const val Toggle = "toggle"
  const val ProtocolVersion = 4
}
